config/routes.rb
Postup::Application.routes.draw do
  devise_for :users
  root :to => "pages#home"
  
  resources :posts do 
    resources :comments
  end

  get "pages/home"
  get "pages/about"

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  mount_uploader :picture, PictureUploader
  
  has_many :comments, dependent: :destroy
  
  validate :name, presence: true,
                   length: { minimum: 5 }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  
private
  def comment_params
    params.require(:comment).permit(:user, :body)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts= Post.all
  end
  
  
  def edit
    @post= Post.find(params[:id])
  end


  def update
    @post= Post.find(params[:id])
    
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
    
  
  def new
    @post = Post.new
  end

  
  def create
    @post = Post.new(post_params)
 
    @post.save
      redirect_to @post
  end

  
  def show
    @post = Post.find(params[:id])
  end

  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:name, :quote, :picture)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>
<p>
	<strong>User:</strong>
	<%= comment.user %>
</p>

<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>

<p>
	<%= link_to "Delete", [comment.post, comment],
				method: :delete,
				data: { confirm: 'Are you sure?' } %>
</p>
<hr>
<% end %>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
<p>
	<%= f.label :user %>
	<%= f.text_field :user, :class => "boxname" %>
</p>

<p>
	<%= f.label :body %>
	<%= f.text_area :body, :class => "boxquote"%>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
		<hr>
		<center>Tony Pham | PostUp | 2013</center>
</div>

app/views/layouts/_header.html.erb
 <div class="navbar navbar-inverse navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
 	  <%= link_to "PostUp", posts_path, :class => "brand" %>
       <div class="nav-collapse collapse">
         <ul class="nav">
             <li><%= link_to "Home", pages_home_path %></li>
             <li><%= link_to "About", pages_about_path %></li>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">Posts <b class="caret"></b></a>
             <ul class="dropdown-menu">
                 <li><%= link_to "All Posts", posts_path %></li>
                 <li><%= link_to "New Post", new_post_path %></li>
               <li class="divider"></li>
               <li class="nav-header">Nav header</li>
               <li><a href="#">Separated link</a></li>
             </ul>
           </li>
         </ul>
         <form class="navbar-form pull-right">
           <input class="span2" type="text" placeholder="Email">
           <input class="span2" type="password" placeholder="Password">
           <button type="submit" class="btn">Sign in</button>
         </form>
       </div><!--/.nav-collapse -->
     </div>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postup</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	
	<div class="container">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		<%= yield %>
	</div>
	
	<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About PostUp</h1>

<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<p>

<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<p>
	
	

app/views/pages/home.html.erb
<h1><p>
	<center>Home</center>
</p>

<p>
	Feeling inspired? Post up a picture and a quote, share it with your friends! Let it be a reminder! Words motivate
</p>	
</h1>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name, :class => "boxname" %>
	</p>
	
	<p>
		<%= f.label :quote %><br>
		<%= f.text_area :quote, :class => "boxquote"%>
	</p>

	<p>
		<%= f.label :picture %><br>
		<%= f.file_field :picture %>
	</p>
	
	<p>
		<%= f.submit %> 
	</p>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Posts<h1>
	
<%= render 'posts/form'%>

app/views/posts/index.html.erb
<h1>Posts</h1>
	
<% @posts.in_groups_of(3) do |group| %>
<div class="row">
		<% group.compact.each do |post| %>
		<div class="span4">
				<center><h2><%= link_to post.name, post%></h2><center>
				<p><%= image_tag post.picture_url, :width => '100%' if post.picture.present? %>
				</p>
				
				<p>
					<center><h4><%= post.quote %></h4></center>
				</p>
				
				<p>
				<%= link_to 'Edit', edit_post_path(post) %> |
				<%= link_to 'Delete', post_path(post),
								method: :delete, data: { confirm: 'Are you sure?' } %>
				</p>
				<hr>
			</div>				
		<% end %>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'posts/form'%>

app/views/posts/show.html.erb
<p>
	<center><h1><%= @post.name %></h1></center>
</p><br>

<p>
	<center><%= image_tag(@post.picture_url, :width => 500) if @post.picture.present? %></center>
</p><br>

<p>
	<center><h3><%= @post.quote %></h3></center>
</p>
<hr>

	<h2>Comments</h2>
	<%= render 'comments/comment' %>
	

	<h2>Add a Comment</h2>
	<%= render 'comments/form' %>
	